### ISSUE TITLE
Add EmployeeForm to NavigationComponent

### ISSUE THREAD

**Issue by ccaylak** [adessoAG/squadmap#11]
Add a EmployeeForm to the navigation bar so you can enter new employees easily with a two clicks.

**Comment by emir-gs** [comment]
I added the EmployeeForm but the date format has to be formatted in order to be accepted by our backend

**Comment by ccaylak** [comment]
Hey well I would appreciate it if you could create your own Issues.
I've assigned myself because I had an idea for the forms.
I wanted to use modals from ngx-bootstrap, this is the reason why it takes so long. 
Have that in mind please, you basically took of work that I had to do now.

**Comment by emir-gs** [comment]
I'm sorry for that. I misunderstand the issue workflow.
Thank you for your hint!
